# fly.toml app configuration file generated for tell-about-image-backend on 2025-03-27T09:19:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tell-about-image-backend'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[processes]
  app = 'run -A ./'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
